# apiVersion: v1
# kind: Namespace
# metadata:
#   name: a

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clientgo-deployment
  namespace: a 
  labels:
    app: clientgo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clientgo
  template:
    metadata:
      labels:
        app: clientgo
    spec:
      containers:
      - name: clientgo
        image: client-go:kubectl
        ports:
        - containerPort: 8080
      #   volumeMounts:
      #     - name: kubeconfig-volume
      #       mountPath: /root
      # volumes: 
      #   - name: kubeconfig-volume
      #     hostPath:
      #       path: /Users/esl-android-eng-00/Desktop/kubeconfigcopy
      #       type: DirectoryOrCreate

---
apiVersion: v1
kind: Service
metadata:
  name: clientgo-service
  namespace: a
spec:
  selector:
    app: clientgo
  type: NodePort
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 30300