apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-deployment
  namespace: a 
  labels:
    app: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: todo-app
        image: todo-app:kubectl
        ports:
        - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: todo-app-service
  namespace: a
spec:
  selector:
    app: todo-app
  type: NodePort
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 30100