service:
  name: clientgo-service
  namespace: a
  type: NodePort
  port: 8080
  targetPort: 8080
  nodePort: 30300


deployment:
    name: clientgo-deployment
    image: client-go:kubectl
    containerPort: 8080
    replicas: 1
    imagePullPolicy: Never
    namespace: a
    label: clientgo